### PR TITLE
Fixed modbus version

### PR DESCRIPTION
**Pull request by samson0v**

### CODE REVIEW

**Comment by leitinhakk** [comment]
hi, how do I update to the new file?

**Comment by LukaszDuss** [comment]
ok, I got it working.

Edit file
`sudo nano /usr/lib/python3/dist-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py`

And implement changes form commit 
[https://github.com/thingsboard/thingsboard-gateway/pull/1160/commits/fcd13b5254ef1585eac1a3475ecd1bbc42cdfdde](url)

Then I had manually reinstall pymodbus with version 3.0.0
`pip install pymodbus==3.0.0 --force-reinstall`

Restart service
`sudo systemctl restart thingsboard-gateway.service`

and it seems to work for now

**Comment by pro100805** [comment]
The link above does not work, can you provide the contents of the file "modbus_connector.py" or a working link?

**Comment by LukaszDuss** [comment]
> The link above does not work, can you provide the contents of the file "modbus_connector.py" or a working link?

image

the link supposed to refer to commit from this pull request (#1160)  :)

**Comment by pro100805** [comment]
After these steps I have the following warning message
[tbgw.txt](https://github.com/thingsboard/thingsboard-gateway/files/12511504/tbgw.txt)
oc:: Ubuntu Server 22.04.3

**Comment by LukaszDuss** [comment]
> After these steps I have the following warning message [tbgw.txt](https://github.com/thingsboard/thingsboard-gateway/files/12511504/tbgw.txt) oc:: Ubuntu Server 22.04.3

Have you confirmed connection between thinsboard CE/PE and gateway?
Have you restarted the service / OS ?

check logs in /var/log/thingsboard-gateway/connector.log

**Comment by pro100805** [comment]
yes 
yes
empty
[tb_gateway.yaml.txt](https://github.com/thingsboard/thingsboard-gateway/files/12511889/tb_gateway.yaml.txt)

**Comment by pro100805** [comment]
tb

**Comment by pro100805** [comment]
I have a new installation of thingsboard-gateway as a package maybe it would be better to install it in another way e.g. from source "github".

**Comment by LukaszDuss** [comment]
> yes yes empty [tb_gateway.yaml.txt](https://github.com/thingsboard/thingsboard-gateway/files/12511889/tb_gateway.yaml.txt)

I have installed GW about 3 weeks ago from .deb also on U22.04
send me your modbus_connector.py
it is weird that u have empty log...

**Comment by pro100805** [comment]
os: 22.04
clean install, thboard 3.5.1 deb +
iot from deb "wget https://github.com/thingsboard/thingsboard-gateway/releases/latest/download/python3-thingsboard-gateway.deb
"
● thingsboard-gateway.service - ThingsBoard Gateway
     Loaded: loaded (/etc/systemd/system/thingsboard-gateway.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-09-06 17:15:19 CEST; 1min 19s ago
   Main PID: 2249 (python3)
      Tasks: 11 (limit: 2220)
     Memory: 47.5M
        CPU: 1min 18.574s
     CGroup: /system.slice/thingsboard-gateway.service
             └─2249 /usr/bin/python3 -c "from thingsboard_gateway.tb_gateway import daemon; daemon()"

Sep 06 17:15:20 thdb-server python3[2249]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/tb_utility/tb_loader.py", line 65, in import_module
Sep 06 17:15:20 thdb-server python3[2249]:     module_spec.loader.exec_module(module)
Sep 06 17:15:20 thdb-server python3[2249]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Sep 06 17:15:20 thdb-server python3[2249]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Sep 06 17:15:20 thdb-server python3[2249]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/modbus/slave.py", line 18, in <module>
Sep 06 17:15:20 thdb-server python3[2249]:     from pymodbus.constants import Defaults
Sep 06 17:15:20 thdb-server python3[2249]: ImportError: cannot import name 'Defaults' from 'pymodbus.constants' (/var/lib/thingsboard_gateway/.local/lib/python3.10/site-packages/pymodbus/constants.py)
Sep 06 17:15:20 thdb-server python3[2249]: ""2023-09-06 17:15:20" - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - _load_connectors - 643 - Connector implementation not found for Modbus Connector"
Sep 06 17:15:20 thdb-server python3[2249]: ""2023-09-06 17:15:20" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 298 - Gateway started."
Sep 06 17:15:21 thdb-server python3[2249]: ""2023-09-06 17:15:21" - |INFO| - [tb_gateway_mqtt.py] - tb_gateway_mqtt - gw_subscribe_to_attribute - 184 - Subscribed to *|* with id 2 for device *"

**Comment by pro100805** [comment]
/var/log/thingsboard-gateway/connector.log

""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 265 - Number of accepted mapping handlers: 3"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 269 - Number of rejected mapping handlers: 0"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 265 - Number of accepted serverSideRpc handlers: 2"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 269 - Number of rejected serverSideRpc handlers: 0"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 265 - Number of accepted connectRequests handlers: 2"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 269 - Number of rejected connectRequests handlers: 0"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 265 - Number of accepted disconnectRequests handlers: 2"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 269 - Number of rejected disconnectRequests handlers: 0"
""2023-09-06 16:43:56" - |ERROR| - [mqtt_connector.py] - mqtt_connector - load_handlers - 251 - Mandatory key 'topicExpression' missing from attributeRequests handler: {"retain": false, "topicFilter": "v1/devices/me/attributes/request", "deviceNameTopicExpression": "${SerialNumber}", "attributeNameJsonExpression": "${sensorModel}"}"
""2023-09-06 16:43:56" - |ERROR| - [mqtt_connector.py] - mqtt_connector - load_handlers - 251 - Mandatory key 'valueExpression' missing from attributeRequests handler: {"retain": false, "topicFilter": "v1/devices/me/attributes/request", "deviceNameTopicExpression": "${SerialNumber}", "attributeNameJsonExpression": "${sensorModel}"}"
""2023-09-06 16:43:56" - |ERROR| - [mqtt_connector.py] - mqtt_connector - load_handlers - 258 - attributeRequests handler is missing some mandatory keys => rejected: {"retain": false, "topicFilter": "v1/devices/me/attributes/request", "deviceNameTopicExpression": "${SerialNumber}", "attributeNameJsonExpression": "${sensorModel}"}"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 265 - Number of accepted attributeRequests handlers: 0"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 269 - Number of rejected attributeRequests handlers: 1"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 265 - Number of accepted attributeUpdates handlers: 1"
""2023-09-06 16:43:56" - |INFO| - [mqtt_connector.py] - mqtt_connector - load_handlers - 269 - Number of rejected attributeUpdates handlers: 0"
""2023-09-06 16:43:57" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:43:58" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:44:00" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:44:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:44:12" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:44:28" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:45:00" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:46:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:48:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:50:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:52:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:54:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:56:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 16:58:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 17:00:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"
""2023-09-06 17:02:04" - |ERROR| - [mqtt_connector.py] - mqtt_connector - _on_connect - 441 - MQTT Broker Connector connection FAIL with error 134 Bad User Name or Password!"

**Comment by pro100805** [comment]
[tb_gateway.yaml.txt](https://github.com/thingsboard/thingsboard-gateway/files/12539572/tb_gateway.yaml.txt)

**Comment by pro100805** [comment]
Hi, after several attempts there is a constant message during the installation process
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

status looks as follows:
 thingsboard-gateway.service - ThingsBoard Gateway
     Loaded: loaded (/etc/systemd/system/thingsboard-gateway.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-09-09 12:18:25 CEST; 3s ago
   Main PID: 1232 (python3)
      Tasks: 11 (limit: 2220)
     Memory: 43.6M
        CPU: 3.146s
     CGroup: /system.slice/thingsboard-gateway.service
             └─1232 /usr/bin/python3 -c "from thingsboard_gateway.tb_gateway import daemon; daemon()"

Sep 09 12:18:27 tb-gw-server python3[1232]: Traceback (most recent call last):
Sep 09 12:18:27 tb-gw-server python3[1232]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/tb_utility/tb_loader.py", line 65, in import_module
Sep 09 12:18:27 tb-gw-server python3[1232]:     module_spec.loader.exec_module(module)
Sep 09 12:18:27 tb-gw-server python3[1232]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Sep 09 12:18:27 tb-gw-server python3[1232]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Sep 09 12:18:27 tb-gw-server python3[1232]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/modbus/slave.py", line 18, in <module>
Sep 09 12:18:27 tb-gw-server python3[1232]:     from pymodbus.constants import Defaults
Sep 09 12:18:27 tb-gw-server python3[1232]: ImportError: cannot import name 'Defaults' from 'pymodbus.constants' (/var/lib/thingsboard_gateway/.local/lib/python3.10/site-packages/pymodbus/>
Sep 09 12:18:27 tb-gw-server python3[1232]: ""2023-09-09 12:18:27" - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - _load_connectors - 643 - Connector implementation not found >
Sep 09 12:18:27 tb-gw-server python3[1232]: ""2023-09-09 12:18:27" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 298 - Gateway started."

/var/log/thingsboard-gateway/connector.log
[log.txt](https://github.com/thingsboard/thingsboard-gateway/files/12565530/log.txt)

**Comment by LukaszDuss** [comment]
ok, now that you have fresh install - have you implemented changes in modbus_connector.py
`sudo nano /usr/lib/python3/dist-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py`

the file should look like that.
image 

then manually reinstall pymodbus with version 3.0.0
`pip install pymodbus==3.0.0 --force-reinstall`

and restart TB-GW service
`sudo systemctl restart thingsboard-gateway.service`

**Comment by pro100805** [comment]
Hi,
installation from deb file, no issues
editing modbus_connector.py is not a problem either
the following message is displayed during the reinstallation process

  WARNING: The scripts pymodbus.console and pymodbus.server are installed in '/home/gde/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

after restart the state looks as follows 

● thingsboard-gateway.service - ThingsBoard Gateway
     Loaded: loaded (/etc/systemd/system/thingsboard-gateway.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-09-18 11:19:27 CEST; 43s ago
   Main PID: 1199 (python3)
      Tasks: 11 (limit: 2220)
     Memory: 41.3M
        CPU: 42.279s
     CGroup: /system.slice/thingsboard-gateway.service
             └─1199 /usr/bin/python3 -c "from thingsboard_gateway.tb_gateway import daemon; daemon()"

Sep 18 11:19:33 tb-gw-server python3[1199]: Traceback (most recent call last):
Sep 18 11:19:33 tb-gw-server python3[1199]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/tb_utility/tb_loader.py", line 65, in import_module
Sep 18 11:19:33 tb-gw-server python3[1199]:     module_spec.loader.exec_module(module)
Sep 18 11:19:33 tb-gw-server python3[1199]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Sep 18 11:19:33 tb-gw-server python3[1199]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Sep 18 11:19:33 tb-gw-server python3[1199]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/modbus/bytes_modbus_downlink_converter.py", line 15, in <module>
Sep 18 11:19:33 tb-gw-server python3[1199]:     from pymodbus.constants import Endian
Sep 18 11:19:33 tb-gw-server python3[1199]: ModuleNotFoundError: No module named 'pymodbus'
Sep 18 11:19:33 tb-gw-server python3[1199]: ""2023-09-18 11:19:33" - |WARNING| - [tb_gateway_service.py] - tb_gateway_service - _load_connectors - 643 - Connector implementation not found >
Sep 18 11:19:33 tb-gw-server python3[1199]: ""2023-09-18 11:19:33" - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 298 - Gateway started."
lines 1-20/20 (END)

**Comment by pro100805** [comment]
maybe there's something wrong with the installation pymodbus
there are ways to fix this?

**Comment by pro100805** [comment]
additional information, I'm using a virtual computer on VMware platform, maybe that's what's causing the difficulties

**Comment by LukaszDuss** [comment]
> additional information, I'm using a virtual computer on VMware platform, maybe that's what's causing the difficulties

I  have mine on vmware ESXi - so suprisingly similar installation and yet idk why it wont work. 
We can comunicate directly and I can try to help you.

**Comment by pro100805** [comment]
well, what I have to do

**Comment by LukaszDuss** [comment]
Send me DM on linkedin

**Comment by LukaszDuss** [comment]
ok, turns out that there is one more thing to do

- change:

# Try import Pymodbus library or install it and import
installation_required = False 

to:
installation_required = True

in:
 /usr/lib/python3/dist-packages/thingsboard_gateway/connectors/modbus/modbus_connector.py

- Reboot OS

- change back to
installation_required = False 

- and reboot OS again

**Pull request merged**
