### PR TITLE
Modbus service

### PR DESCRIPTION
**Pull request by dyosick**
The service supports the following Modbus protocols: RTU, ASCII, TCP, UDP.
The service can simultaneously communicate with several Modbus servers, each of them you can configure separately.

The supported functions:
- Read Coils (code 1)
- Read Discrete Inputs (code 2)
- Read Multiple Holding Registers (code 3)
- Read Input Registers (code 4)

### CODE REVIEW

**Comment by dyosick** [comment]
What is better way to provide configuration documentation?

**Comment by mp-loki** [comment]
The documentation resides under https://github.com/thingsboard/thingsboard.github.io
docs/iot-gateway directory

**Comment by dyosick** [comment]
Added documentation. Here is [PR](https://github.com/thingsboard/thingsboard.github.io/pull/99)
Is there something else what I can or need to do to apply my PR? : )

**Comment by dyosick** [comment]
GUI PR is [there](https://github.com/thingsboard/thingsboard/pull/712).

**Comment by ashvayka** [comment]
Impressive! Дякую!

**Comment by pavellzubkov** [comment]
Hi. How it works? If i try add modbus rtu to gateway over thingsboard gui i have modExtensionError

> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "host" (class org.thingsboard.gateway.extensions.modbus.conf.transport.ModbusRtuTransportConfiguration), not marked as ignorable (7 known properties: "dataBits", "timeout", "encoding", "stopBits", "portName", "parity", "baudRate"]) at [Source: N/A; line: -1, column: -1] (through reference chain:

**Comment by pavellzubkov** [comment]
i make export extensions configuration , then delete host and port and get next error 

> java.lang.RuntimeException: MBS connection failed! at org.thingsboard.gateway.extensions.modbus.ModbusClient.connect(ModbusClient.java:119) at java.util.ArrayList.forEach(ArrayList.java:1257) at org.thingsboard.gateway.extensions.modbus.DefaultModbusService.init(DefaultModbusService.java:64) at org.thingsboard.gateway.service.TenantServiceRegistry.updateExtensionConfiguration(TenantServiceRegistry.java:83) at org.thingsboard.gateway.service.DefaultTenantManagerService.lambda$init$0(DefaultTenantManagerService.java:64) at org.thingsboard.gateway.service.gateway.MqttGatewayService.updateConfiguration(MqttGatewayService.java:514) at org.thingsboard.gateway.service.gateway.MqttGatewayService.onGatewayAttributesGet(MqttGatewayService.java:495) at org.thingsboard.gateway.service.gateway.MqttGatewayService.lambda$onMessage$17(MqttGatewayService.java:430) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.io.IOException: Port [ttyUSB0] cannot be opened or does not exist - Valid ports are: [ttyUSB0] at com.ghgande.j2mod.modbus.net.SerialConnection.open(SerialConnection.java:127) at com.ghgande.j2mod.modbus.facade.ModbusSerialMaster.connect(ModbusSerialMaster.java:80) at org.thingsboard.gateway.extensions.modbus.ModbusClient.connect(ModbusClient.java:110) ... 12 more

**Comment by pavellzubkov** [comment]
`Port [ttyUSB0] cannot be opened or does not exist - Valid ports are: [ttyUSB0]`!

**Comment by dyosick** [comment]
Hi @pavellzubkov could you create an issue and describe there steps how to reproduce? From your description I don't understand from which configuration section you deleted host/port fields.

As for the ttyUSB0 error, maybe there is some misconfiguration of a serial port. Could you provide more information about it? (it would be great if you create another issue).

**Comment by dyosick** [comment]
@pavellzubkov  I fixed extra fields [in this PR](https://github.com/thingsboard/thingsboard/pull/729)
Also I retested the MODBUS RTU connection and if a physical port configuration is set up properly the gateway will work as expected.

**Comment by BIT-masterpy** [comment]
Where is the documentation for Modbus extension?

**Comment by dyosick** [comment]
@BIT-masterpy I answered in [the ticket](https://github.com/thingsboard/thingsboard-gateway/issues/76).

**Pull request merged**
