### PR TITLE
Feature/fix opcua asyncio

### PR DESCRIPTION
**Pull request by wilterdinkrobert**
See commits

### CODE REVIEW

**Comment by samson0v** [comment]
Hi @wilterdinkrobert, try your PR and I can't get value from nodes (for example Root.Objects.Simulation.Counter) with config:
```
        "deviceNodePattern": "Root\\.Objects\\.Simulation",
        "deviceNamePattern": "OPC-UA Device1111",
        "attributes": [
          {
            "key": "temperature °C",
            "path": "${Counter}"
          }
        ],
        ....
```
зображення

It seems that there is some problem with node findings.

**Comment by wilterdinkrobert** [comment]
@samson0v I don't think this type of relative path resolving was implemented for the asyncua based connector. Was this working before?

**Comment by wilterdinkrobert** [comment]
@samson0v I've fixed the issue and found + fixed some other things. Please have a look again.

**Comment by samson0v** [comment]
@wilterdinkrobert, try your fixes, and there is still a problem with finding nodes. 

For example:
```
        "deviceNodePattern": "Root\\.Objects\\.Simulation",
        "deviceNamePattern": "OPC-UA Device1111",
        "attributes": [
          {
            "key": "temperature °C",
            "path": "${Test.Counter}"
          }
        ],
        "timeseries": [
        ],
```
зображення
And connector can't find the node.

It should be noted that before fixes, it worked fine.

**Comment by wilterdinkrobert** [comment]
@samson0v I've followed the 'old' [OPCUA path specification](https://thingsboard.io/docs/iot-gateway/config/opc-ua/), i.e.: `"path": "${Test\\.Counter}"`. Is that not correct?

**Pull request merged**
