### PR TITLE
Connecting Extended Configuration by Multithread Connection

### PR DESCRIPTION
**Pull request by felix-ma**
Mqtt and Modbus protocol extensions, adding multithreaded connections, and fixing bugs that will not retry connections if thingsboard does not start when gateway starts

### CODE REVIEW

**Comment by guodaxia103** [comment]
干得不错，非常棒

**Comment by liuli283** [comment]
nice

**Comment by caoyingde** [comment]
NB

**Comment by zbeacon** [comment]
Hi, @felix-ma 

We have released new version of the Gateway based on Python. Please consider adding your functionality to new version. If you are not familiar with Python I can guide you through the required changes or port your changes. Which one do you prefer?

**Pull request closed without merging**
