### PR TITLE
Added ability to process incoming data without any decoding.

### PR DESCRIPTION
**Pull request by devaskim**
Discussion: #942

### CODE REVIEW

**Comment by samson0v** [comment]
Hi @devaskim, after review, I think your changes make no sense because the connector has to be able to process any type of data with a specific config but not a whole data.

If you are interested in releasing this feature, please look at the socket converter and how it processes raw data and its configuration.

Nonetheless, we will add this feature to MQTT Connector as soon as possible.

**Comment by devaskim** [comment]
I am not sure what understood your arguments. So my question is what are you going to implement in MQTTConnector to cover #942 case and how your implementation would differ from mine?

**Comment by devaskim** [comment]
IMHO, the role of mqtt connector is to provide connection between mqtt broker/data converters and Thingsboard server. At the moment mqtt connector limits gateway's users in JSON formatted data. If it wasn't so, we couldn't see #942

**Comment by samson0v** [comment]
@devaskim config section will look like this:
```
{
    "type": "raw",
    "key": "[:]",
    "value": "[0:2]"
}
```
and the same for `deviceName` and `deviceType` parameters.

**Comment by devaskim** [comment]
@samson0v Thanks for your explanation and for spending on me your time. This will be great feature. 

But to switch between json and raw traffic any way the mqtt connector will need some configuration option called `raw` as in your example above or something other name. I just tried to introduce this option now instead of near or further future.

Close the PR if you don't need this changes. And good luck!

**Pull request closed without merging**
